name: Duplicate code

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check for duplicate files
        run : ./duplicate.sh
        id: duplicate
        shell: bash
      - name: Get the filenames
        run: echo "${{ steps.duplicate.outputs.duplicate_filename }}"
        if:  steps.duplicate.outputs.duplicate_filename != '0'
